### ISSUE TITLE
Why "range covered by prompt are set to 0" in noised latents?

### ISSUE THREAD

**Issue by FacePoluke** [Plachtaa/seed-vc#15]
Thank you for your open-source work. I have a question: why are the parts of the noisy latents that are covered by the prompt set to 0?  https://github.com/Plachtaa/seed-vc/blob/46f5848e266281501941aa78ea849012c43f5c65/modules/flow_matching.py#L133

**Comment by Plachtaa** [comment]
prompt component should be kept constant along different diffusion steps

**Comment by FacePoluke** [comment]
> prompt component should be kept constant along different diffusion steps

you mean no noise should be added to the latents of the prompt component ?

**Comment by Plachtaa** [comment]
It's long to explain, you can look into training code or paper for detail
