### ISSUE TITLE
DiT_step_440000_seed_v2

### ISSUE THREAD

**Issue by lifeng5658** [Plachtaa/seed-vc#16]
I don't have this file, please give me the download link directly. I am using the WEBUI version
![微信图片_20240923145616](https://github.com/user-attachments/assets/7779b3a9-073e-4357-a763-d55fe3416b52)
![微信图片_20240923145621](https://github.com/user-attachments/assets/a9fdc256-c3c6-4b1b-803f-076562d858ca)

**Comment by Plachtaa** [comment]
Legacy checkpoints are deleted by default, please update your repo for the link to currently provided version
