### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by deyituo** [Plachtaa/seed-vc#18]
赞！这个项目，有一些vc的指标吗，比如seed-tts-eval

**Comment by Plachtaa** [comment]
感谢你的提醒，这个还没做，不过会放进TODO里

**Comment by Plachtaa** [comment]
benchmark和与其它模型的比较已经添加到readme中

**Comment by deyituo** [comment]
赞！要是有seed-tts-eval中文集合的测试会更好些

**Comment by Plachtaa** [comment]
有道理，中文会做的

**Comment by Plachtaa** [comment]
Singing voice conversion的benchmark用中文做了
