### ISSUE TITLE
JDC F0 用途

### ISSUE THREAD

**Issue by liziru** [Plachtaa/seed-vc#20]
我看到配置文件中有F0_path: "modules/JDC/bst.t7"，请问这个模型用途是什么，是打算用在流式推理中吗，请问这个模型估计F0的效果怎么样？

**Comment by Plachtaa** [comment]
这个效果不如RVC那边的rmvpe好，已经弃用了

**Comment by liziru** [comment]
> 这个效果不如RVC那边的rmvpe好，已经弃用了

rmvpe计算量太大，如果流式推理是不是跑步起来，有计算量小一点的nn f0方法推荐吗，传统f0方法感觉效果不太好

**Comment by Plachtaa** [comment]
目前的考虑是流式推理应该用不带F0输入的版本

**Comment by liziru** [comment]
> 目前的考虑是流式推理应该用不带F0输入的版本

嗯 jdc f0应该比传统方法效果好一些吧

**Comment by Plachtaa** [comment]
> > 目前的考虑是流式推理应该用不带F0输入的版本
> 
> 嗯 jdc f0应该比传统方法效果好一些吧

这个就不清楚了

**Comment by liziru** [comment]
> > > 目前的考虑是流式推理应该用不带F0输入的版本
> > 
> > 
> > 嗯 jdc f0应该比传统方法效果好一些吧
> 
> 这个就不清楚了

好的谢谢老兄
