### ISSUE TITLE
这个文件无法下载

### ISSUE THREAD

**Issue by ninjaweiwei** [Plachtaa/seed-vc#21]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\PR-SeedVC-ComfyUI-93433be3\\checkpoints\\Seed-VC\\DiT_step_315000_seed_v2_wavenet_online_pruned.pth'

**Comment by Plachtaa** [comment]
legacy checkpoint isbnot provided anymore. please pull the latest repo or contact your comfy ui author
