### ISSUE TITLE
Hugging Face线上效果和本地推理效果不一致

### ISSUE THREAD

**Issue by Ranzige** [Plachtaa/seed-vc#25]
感谢作者的无私开源，我首先在Hugging Face线上测试了一下，觉得效果很好，git到本地推理后，相同的参考音频和参数设置，推理的结果比线上的要差一些。

**Comment by Plachtaa** [comment]
如果可以的话，参数，音频和推理结果发一下，我会查看推理脚本是否有潜在的逻辑bug

**Comment by Ranzige** [comment]
[推理结果.zip](https://github.com/user-attachments/files/17290578/default.zip)
这是推理结果，参数设置：-diffusion-steps 10 --length-adjust 1.0 --inference-cfg-rate 0.7 --f0-condition False  --auto-f0-adjust False  --semi-tone-shift 0

**Comment by Plachtaa** [comment]
source和reference也发一下

**Comment by Ranzige** [comment]
[Uploading 参考音频&源音频.zip…]()

**Comment by Ranzige** [comment]
[参考音频&源音频.zip](https://github.com/user-attachments/files/17290642/default.zip)

**Comment by Plachtaa** [comment]
我这边重新推理了几遍没有听出来什么差别，code也有检查过一遍，和huggingface的推理是一致的
diffusion存在随机性，建议多跑几遍或者提高步数到20或30会好一些
