### ISSUE TITLE
Is there an implementation for real-time inference (even if it's not very real-time)?

### ISSUE THREAD

**Issue by momoGBG** [Plachtaa/seed-vc#29]
We can try it together and optimize it

**Comment by Plachtaa** [comment]
Thanks for your offer. I will consider releasing it in a few days

**Comment by Plachtaa** [comment]
Real time inference GUI has been released, latency is around 1~2 seconds but quality is generally satisfying. 
We will be looking for ways to reduce it in the future, and meanwhile any solution for inference speed increase is highly welcomed and appreciated      orz

**Comment by momoGBG** [comment]
> Real time inference GUI has been released, latency is around 1~2 seconds but quality is generally satisfying. We will be looking for ways to reduce it in the future, and meanwhile any solution for inference speed increase is highly welcomed and appreciated orz

Thank you for your implementation! I pulled the latest code and noticed that the "requirement.txt" hasn't been updated and that "'configs/inuse/config.json'" and "'configs/config.json'" are missing.

**Comment by Plachtaa** [comment]
Thanks for your precious feedback. I have updated both config files and requirements.txt
