### ISSUE TITLE
会有语音克隆的版本吗

### ISSUE THREAD

**Issue by TheHonestBob** [Plachtaa/seed-vc#3]
我非音频方向的，想问一下该架构适合语音克隆吗？或者未来会有语音克隆的版本计划吗

**Comment by Plachtaa** [comment]
zero shot就是可以语音克隆的

**Comment by TheHonestBob** [comment]
> zero shot就是可以语音克隆的

我看放出的demo，是输入目标音频+prompt音频，是否能够支持text+prompt音频，目前来看如果我想实现语音克隆，貌似需要先tts，然后使用seed-vc项目

**Comment by TheHonestBob** [comment]
> voice conversion和text to speech是不同的task，这个只能clone timbre

voice conversion和text to speech这个我明白，我的意思是voice clone，我理解的voice clone是输入text+prompt音频，然后输出prompt音频音色的text音频

**Comment by O-O1024** [comment]
> > voice conversion和text to speech是不同的task，这个只能clone timbre
> 
> voice conversion和text to speech这个我明白，我的意思是voice clone，我理解的voice clone是输入text+prompt音频，然后输出prompt音频音色的text音频

你并不明白!

**Comment by TheHonestBob** [comment]
> > > voice conversion和text to speech是不同的task，这个只能clone timbre
> > 
> > 
> > voice conversion和text to speech这个我明白，我的意思是voice clone，我理解的voice clone是输入text+prompt音频，然后输出prompt音频音色的text音频
> 
> 你并不明白!

你明白一个给我看看

**Comment by TheHonestBob** [comment]
> @TheHonestBob 输入文本最后出语音不就是使用了text to speech吗？

输入文本出来音频是TTS
输入文本+prompt音频是语音克隆

**Comment by jiaweiru** [comment]
你理解的语音克隆应该指的是zero-shot的TTS任务，就Seed-TTS的论文来看，这俩用的架构还是有点区别的
