### ISSUE TITLE
typeError:BigVGAN.__init_subclass__() takes no keyword arguments 

### ISSUE THREAD

**Issue by weifj0212** [Plachtaa/seed-vc#31]
ubuntu下运行app.py时，出现上述错误，又遇到这样问题的吗？如何解决？

**Comment by Plachtaa** [comment]
请发完整报错信息

**Comment by weifj0212** [comment]
![1729672406659](https://github.com/user-attachments/assets/765fd5ab-e848-45d1-9d21-84ab786a1579)

**Comment by Plachtaa** [comment]
升级torch至2.3.0可以解决此问题

**Comment by weifj0212** [comment]
升级后还是报一样的错误

**Comment by Plachtaa** [comment]
请参照BigVGAN原repo的要求
![image](https://github.com/user-attachments/assets/2be0710c-506e-4824-92f6-ac36fe67558d)
