### ISSUE TITLE
reference audio 的 mel 谱作为 inference 时的 prompt 参数：它是否是必须的？

### ISSUE THREAD

**Issue by Aijohc** [Plachtaa/seed-vc#33]
首先，感谢你们开源了这么好用的模型！这是我目前能找到的最佳 VC 模型。

我有一个问题，关于 reference audio 的 mel 谱作为 inference 时的 prompt 参数：它是否是必须的？在我的理解中，音色是一个全局的特征，同一个人的不同 reference audio 中应该基本保持一致，即代码中的 style2。我希望能仅使用 style2 作为 speaker prompt，而不使用 reference audio 的 mel 谱。实际上，我尝试过将 prompt 替换为 zeros 或 randn，生成的音频效果差别不大。因此，我想问是否可以去掉 mel 谱，仅使用 style2 作为 prompt？这样做是否会有潜在问题或潜在的好处（如可以提高音频的最大长度）？

另外，我没有找到这个仓库对应的论文或说明文档，想请问是否有相关资源可以参考呢？

**Comment by Plachtaa** [comment]
请参照README，cosyvoice及SeedVC之所以能在SECS指标上超过openvoice十个点以上，正是因为有reference mel作为context，有兴趣的话你可以试一下把reference mel去除后similarity会掉多少

**Comment by Aijohc** [comment]
okk，感谢回复
