### ISSUE TITLE
Causes of Extended Audio Duration After Conversion and Solutions

### ISSUE THREAD

**Issue by Bella-Tim** [Plachtaa/seed-vc#40]
After conversion, the audio duration is different from the original, and it has become longer. What causes this issue? Besides adjusting the playback speed, are there any other methods to keep the converted audio duration the same as the original?

**Comment by Plachtaa** [comment]
Please share an example of before/after conversion, and how long does the conversion result is longer than original

**Comment by Bella-Tim** [comment]
For example, with this audio clip, I used a Trump model. The original was 4 seconds, but the converted version is 5 seconds.
model audio:
  https://drive.google.com/file/d/1qHnQuMHSQ1RmlgasdoPAl7utqnN4H5Sp/view?usp=sharing
original audio :
 https://drive.google.com/file/d/1O1AHT24W2_9bTQY_SWK5ighg5RHPmQF1/view?usp=sharing

**Comment by Plachtaa** [comment]
please share your converted audio as well, as the audio you shared here seems to only have original audio and reference audio

**Comment by Bella-Tim** [comment]
converted audio ：
https://drive.google.com/file/d/1FtKZxO0KMKB8TJptKAig47GlGi3mZQh-/view?usp=sharing

**Comment by Plachtaa** [comment]
I am noticing your original audio has a length of 4.80 seconds, while the conversion result is of 5.80 seconds, and it sounds slower that source
However, I tried conversion on the web app and get a result of 4.79 seconds.
Please make sure you have correctly set the length adjust argument to 1.0

**Comment by Bella-Tim** [comment]
My bad, I overlooked this. I kept thinking I had set it to 1.0, but it was actually set to 1.2. Thank you.
