### ISSUE TITLE
Minimum Required PC specs? 

### ISSUE THREAD

**Issue by Lenos500** [Plachtaa/seed-vc#43]
Hello,  it would be nice if you could tell us what is the minimum pc specs needed to run this model?

Cpu, ram, gpu etc.....

Thanks!

**Comment by Plachtaa** [comment]
I would suggest a NVIDIA GPU with minimum 4GB VRAM

**Comment by Lenos500** [comment]
> I would suggest a NVIDIA GPU with minimum 4GB VRAM

Thanks I had to ask because the hugging face demo uses 69gb ram plan I think and it still needs 5-7 seconds for 1 inference so I thought it might be demanding.
