### ISSUE TITLE
Dimension mismatch bug in app.py

### ISSUE THREAD

**Issue by YangStark** [Plachtaa/seed-vc#46]
File "E:\seed-vc-main\app.py", line 311, in voice_conversion
    output_wave = crossfade(previous_chunk.cpu().numpy(), vc_wave[0].cpu().numpy(), overlap_wave_len)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\seed-vc-main\app.py", line 134, in crossfade
    chunk2[:overlap] = chunk2[:overlap] * fade_in + chunk1[-overlap:] * fade_out
                       ~~~~~~~~~~~~~~~~~^~~~~~~~~
ValueError: operands could not be broadcast together with shapes (6400,) (8192,)

updated crossfade to this and the bug is now resolved.

def crossfade(chunk1, chunk2, overlap):
    # Ensure overlap is not greater than the length of either chunk
    overlap = min(len(chunk1), len(chunk2), overlap)

    # Create fade-in and fade-out arrays
    fade_out = np.cos(np.linspace(0, np.pi / 2, overlap)) ** 2
    fade_in = np.cos(np.linspace(np.pi / 2, 0, overlap)) ** 2

    # Apply crossfade by combining overlapping sections
    chunk2[:overlap] = chunk2[:overlap] * fade_in + chunk1[-overlap:] * fade_out
    return chunk2

**Comment by Plachtaa** [comment]
please attach the samples and generation params that cause your error, thanks

**Comment by TomSuen** [comment]
Hi, could you tell me your pytorch version? Thx @YangStark 
I tried many version but got different error each time

**Comment by YangStark** [comment]
Sorry for the late reply, I'm using pytorch 2.5.1, I also change the requirement script because it defaulted to the CPU version and I had to manually install GPU version.

**Comment by YangStark** [comment]
Another thing I noticed is that if I want to change the voice to a two-hour long audio file, it spits out content too long not supported error and the output takes very long and cannot finish. For reference I'm using a 3060ti.

**Comment by ymmbb8882ymmbb** [comment]
在voice_conversion函数内加一个   hop_length = 256 if not f0_condition else 512  防止在上面的加载中进行覆盖并将
    max_context_window = sr // hop_length * 30
    overlap_frame_len = 16
    overlap_wave_len = overlap_frame_len * hop_length
    bitrate = "320k"
    迁到函数里。

**Comment by ymmbb8882ymmbb** [comment]
在voice_conversion函数内加一个 hop_length = 256 if not f0_condition else 512 防止在上面的加载中进行覆盖。
max_context_window = sr // hop_length * 30
Overlap_frame_len = 16
Overlap_wave_len = Overlap_frame_len * hop_length
bitrate = "320k"
迁移到函数里。
