### ISSUE TITLE
请教一下这是什么原因呢？是onnxruntime的问题吗？

### ISSUE THREAD

**Issue by Nuyoah111111** [Plachtaa/seed-vc#49]
![image](https://github.com/user-attachments/assets/39a1cb15-7e2d-4787-aa33-73247cb469a4)

**Comment by Plachtaa** [comment]
目前已经没有onnxruntime的依赖了，按照你给的截图很难判定这个message源自哪里

**Comment by Nuyoah111111** [comment]
> 目前已经没有onnxruntime的依赖了，按照你给的截图很难判定这个message源自哪里

现在是另一个问题
![image](https://github.com/user-attachments/assets/acc3ef28-3508-48a5-b370-92c010846670)
![image](https://github.com/user-attachments/assets/3a4cf606-c89d-4ce8-82d3-54d5da3c0e98)
这里为什么我会出现这个错误呢

**Comment by Nuyoah111111** [comment]
> eval的数据少了个index.tsv忘记给了，回头再修吧

190-192那里为什么要去读取那些音频文件的名称呢

**Comment by Plachtaa** [comment]
你为什么要跑eval.py，如果你是相关研究人员，想要查询结果真实性的话，我觉得这些你自己应该都会弄
如果你只是想用，跑app.py就行了

**Comment by Nuyoah111111** [comment]
> 你为什么要跑eval.py，如果你是相关研究人员，想要查询结果真实性的话，我觉得这些你自己应该都会弄 如果你只是想用，跑app.py就行了

我只是使用模型的话就直接跑app.py吗

**Comment by Plachtaa** [comment]
是的
