### ISSUE TITLE
在执行的时候报这个错误了，请问怎么解决

### ISSUE THREAD

**Issue by qiudaoyuzkx** [Plachtaa/seed-vc#56]
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by Plachtaa** [comment]
specify script name, arguments passed and audio samoles used pls

**Comment by mytait** [comment]
this seems the same problem as  #37 

it happens when the source audio is longer than 30 seconds. Then the code crashes. The reference audio can be any length.

**Comment by Plachtaa** [comment]
inference.py now supports long form generation. You will not meet such problem anymore
