### ISSUE TITLE
关闭F0时片段丢失

### ISSUE THREAD

**Issue by Minou43** [Plachtaa/seed-vc#57]
关闭f0时中间会有小片段丢失，试了下发现reference或者src太大时才出现这个问题。用的第一个example的配置，目前试下来15秒没有这个问题，20秒会开始出现。

**Comment by Plachtaa** [comment]
可以分享一下引发问题的source和reference音频吗

**Comment by Minou43** [comment]
[example.zip](https://github.com/user-attachments/files/17922624/example.zip)
比如这个，用的第一个example的配置，输出视频在第9秒和17秒少了一段

**Comment by Minou43** [comment]
好的大佬，看到training出来了，为啥training后做inference还需要参考音频呢？对这个参考音频有什么要求没？

**Comment by Plachtaa** [comment]
查了一下是hop length不一致的问题，现在已经修复
