### ISSUE TITLE
和前一版做了些比较，我试验了异性之间转换声音，为什么感觉第一版的零样本推理会比新版的效果好呢。

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [Plachtaa/seed-vc#58]
和前一版做了些比较，我试验了异性之间转换声音，为什么感觉第一版的零样本推理会比新版的效果好呢。

**Comment by Plachtaa** [comment]
你指的哪个是第一版哪个是新版😂

**Comment by ymmbb8882ymmbb** [comment]
今天更新的这一版和没有更新之前的

**Comment by ymmbb8882ymmbb** [comment]
今天更新的这个版本和更新之前的做的比较

**Comment by ymmbb8882ymmbb** [comment]
今天更新的这个版本和更新之前的版本做的比较。

**Comment by ymmbb8882ymmbb** [comment]
今天更新的这版和更新之前的版本。做的比较是异性之间的说话克隆，source:男音色，reference:女音色。最新版本的克隆的音色音调不太像reference，音调太粗，需变调。之前版本音色更像一些。以上仅是自己做的单一比较，如有不实之处，还望谅解。

**Comment by ymmbb8882ymmbb** [comment]
好的，了解了，但是并没有看到tiny模型DiT_uvit_tat_xlsr_ema.pth在哪里调用

**Comment by Plachtaa** [comment]
你运行的是哪个script，传入的参数是什么

**Comment by ymmbb8882ymmbb** [comment]
运行是app.py ,传入参数为两个文件，分别对应source和reference

**Comment by Plachtaa** [comment]
app.py的模型和之前是一模一样的

**Comment by ymmbb8882ymmbb** [comment]
[对比.zip](https://github.com/user-attachments/files/17932422/default.zip)
是的，模型是和之前是一致的。是否是一些其他模型导致的呢？

**Comment by Plachtaa** [comment]
你说的对，是VC的一个vocoder用错了，马上修

**Comment by ymmbb8882ymmbb** [comment]
感谢您的回复与解答。那么如果没有微调模型的需求，可否继续使用之前版本呢？

**Comment by Plachtaa** [comment]
app.py已经回滚到之前的版本了，当然如果你不需要微调的话继续用之前的应该是没问题的
感谢你的耐心反馈🙏
