### ISSUE TITLE
Streaming inference and speech token extraction

### ISSUE THREAD

**Issue by vitreo12** [Plachtaa/seed-vc#6]
Hello! 

First off, amazing project! I cloned it and got it up and running quite easily. 

I have a question about the streaming inference mentioned in the readme. Is this to allow to run inference on real-time audio, instead of one shot conversion? I ran some benchmarks and it seems to me that the bottleneck is with the cosyvoice speech token extraction. I wonder how could this work with real-time audio? The target voice speech tokens can be extracted before inference time, but I wonder how would you approach extracting the one for the source voice. Do you plan on a different architecture to make it work for real-time audio streams?

Thank you and have a great day!

**Comment by Plachtaa** [comment]
we already have a solution for streaming inference, but we are still on the way of increasing stability and inference speed before releasing it

**Comment by Plachtaa** [comment]
Streaming inference GUI has been released
