### ISSUE TITLE
Feedback: The webpage cannot be opened normally

### ISSUE THREAD

**Issue by tt8398** [Plachtaa/seed-vc#60]
Webpage https://huggingface.co/spaces/Plachta/Seed-VC Unable to open normally，Please fix it

**Comment by Plachtaa** [comment]
I can still view the website. If you are meeting HF 500 internal error then it is quite normal. If you are in mainland China please use VPN. Or else please describe your issue

**Comment by tt8398** [comment]
![WX20241127-233827@2x](https://github.com/user-attachments/assets/3270cf3b-9379-4c3a-8713-cf9b3b787a52)
 Have been used for VPN try to open the web site https://huggingface.co/spaces/Plachta/Seed-VC, but still failed. Don't know how to solve it?
