### ISSUE TITLE
使用app_svc.py指向training得到的checkpoint好像没起作用

### ISSUE THREAD

**Issue by Minou43** [Plachtaa/seed-vc#62]
试了下新的training，效果有了明显提升，效果比many shot还好，很赞！就是似乎只有用inference.py的脚本时生效，用app_svc.py的话即使加载了新的checkpoint，好像出来的结果还是和原来一样，参数一样时和inference.py出来的结果有明显差异，是不是svc GUI还没支持training？

**Comment by Plachtaa** [comment]
把你的cmd推理传入的参数和app.py用的参数都发一下

**Comment by Plachtaa** [comment]
看了一下是因为两边的F0 extractor的threshold不一样，inference.py是0,03，但是app.py 和app_svc.py都是0.5
我把app.py中的threshold设为0.03之后就能得到和inference.py一样的结果了
这个我不清楚差距有多大，如果你觉得前者更好的话我暂时先把所有的都改成0.03

**Comment by Minou43** [comment]
嗯，样本小的话0.5出来的音质差很多，要不要考虑把threshold做为参数？

**Comment by Plachtaa** [comment]
现在所有地方都设为0.03了，这个没必要改
