### ISSUE TITLE
training音频超过30s无法训练

### ISSUE THREAD

**Issue by Minou43** [Plachtaa/seed-vc#70]
放了个长一点的training音频，然后就不停打印Audio xxx.mp3 is too short or too long, skipping，用小于30s的就没问题

**Comment by Minou43** [comment]
顺便问下大佬，training一次之后怎么继续接着training？

**Comment by Plachtaa** [comment]
用同样的config和run name启动就行了，检查点会自动加载最新的
音频长度有限制这个一般是常识哈😂，要自己prepare的，这个应该要在readme里提一下

**Comment by Minou43** [comment]
嗯好的谢谢，看看例子还以为能自动处理
