### ISSUE TITLE
Question about the audio quality of the output file

### ISSUE THREAD

**Issue by GUUser91** [Plachtaa/seed-vc#71]
Is there a reason why the audio quality for the output file has this sort of robotic filter sound? Diffusion is set to 100.
Input file:
https://vocaroo.com/1nuRtxDNgplN
Reference audio:
https://vocaroo.com/14kQeBJTgC1O
Output file:
https://vocaroo.com/15X0wVE7tXKN
Output file with finetuned model:
https://vocaroo.com/1mMDIhUi2ZrI

**Comment by Plachtaa** [comment]
> Is there a reason why the audio quality for the output file has this sort of robotic filter sound? Diffusion is set to 100. Input file: https://vocaroo.com/1nuRtxDNgplN Reference audio: https://vocaroo.com/14kQeBJTgC1O Output file: https://vocaroo.com/15X0wVE7tXKN Output file with finetuned model: https://vocaroo.com/1mMDIhUi2ZrI

are you using fp16? disabling it would get better audio quality

**Comment by Plachtaa** [comment]
I have made a change just now that fp16 is only applied to diffusion module but vocoder still do fp32. It should make the audio quality better

**Comment by GUUser91** [comment]
This is how the output file sounds like with the vocoder update. The robotic filter still remains.
https://vocaroo.com/1l09jLzWxEDM

**Comment by Plachtaa** [comment]
which model are u using?
how many steps have you trained?
what's the size the dataset?

**Comment by GUUser91** [comment]
The output file from my previous post is the base model. 
This is how it sounds with my finetune model that I made hours ago. I used the default settings for the finetune model that I took from the github homepage. The dataset is 25 minutes.
```
python train.py --config <path-to-config> --dataset-dir <path-to-data> --run-name <run-name> --batch-size 2 --max-steps 1000 --max-epochs 1000 --save-every 500 --num-workers 0
```

Output file for the finetune model
https://vocaroo.com/1csmqTqBt3uZ

Can you post a vocaroo link for your output file? I'm curious as to why I still get the robotic audio quality and you don't.

**Comment by Plachtaa** [comment]
try it yourself on huggingface space, at least for me I can't tell there is any robotic voice, probably your standard is so high that the model cannot meet

**Comment by GUUser91** [comment]
Okay, I understand. This is how it sounds like from the space demo.
https://vocaroo.com/18PhzHe157sk
