### ISSUE TITLE
How to load vocos?

### ISSUE THREAD

**Issue by TomSuen** [Plachtaa/seed-vc#72]
According to the code in `app_vc.py`
```
elif vocoder_type == "vocos":
        vocos_config = yaml.safe_load(open(model_params.vocoder.vocos.config, 'r'))
        vocos_path = model_params.vocoder.vocos.path
        vocos_model_params = recursive_munch(vocos_config['model_params'])
```
vocos_config.yaml should have the key `model_params`

but I haven't found any model satisfied on huggingface

**Comment by Plachtaa** [comment]
we have not trained a good enough vocos to publish

**Comment by TomSuen** [comment]
> we have not trained a good enough vocos to publish

Thanks
