### ISSUE TITLE
是否支持文本转换语音

### ISSUE THREAD

**Issue by Jumao-OC** [Plachtaa/seed-vc#83]
你好，此模型是否支持文本转换语音这样的功能。

**Comment by Plachtaa** [comment]
you can connect this model to any TTS API or model to achieve "zero-shot TTS" similar to OpenVoice

**Comment by GUUser91** [comment]
I use MaskGCT and Hailuo.AI Audio for text for speech. Hailuo.AI Audio is free for now, but I'm sure Minimax will put it behind a paywall soon.

**Comment by Jumao-OC** [comment]
> you can connect this model to any TTS API or model to achieve "zero-shot TTS" similar to OpenVoice、、Thanks for the answer, so how can I use this model to connect to the TTS API

**Comment by Mofa-Xingche** [comment]
> Hello, does this model support such a feature as text-to-speech.

tts here bro
https://github.com/fishaudio/Bert-VITS2

**Comment by Jumao-OC** [comment]
> > Hello, does this model support such a feature as text-to-speech.
> > @Jumao-OC
> > tts here bro
> > https://github.com/fishaudio/Bert-VITS2

Thank you for your suggestion. It seems that this project only supports Chinese, and I need more languages

**Comment by Mofa-Xingche** [comment]
OK , Bert vits  support JP EN China

**Comment by Jumao-OC** [comment]
> OK , Bert vits support JP EN China

Can you tell me how to use this model? I only found the webui_preprocess. py file on the official website, but it's just a Python file

**Comment by Mofa-Xingche** [comment]
dataset text file Example:
esd.list
↓


{wav_path}|{speaker_name}|{language}|{text}
派蒙_1.wav|派蒙|ZH|前面的区域，以后再来探索吧！
tom-Brown_1.wav|tomBrown|EN|I am like beatles,you are not like? really?
佐藤さん_１番.wav|佐藤|JP|深海？いや深海の事なんかようわからんし、すまんね
佐藤さん_2番.wav|佐藤|JP|早くご飯つくって～！お腹すいた

**Comment by Jumao-OC** [comment]
> dataset text file Example:数据集文本文件示例： esd.list静电放电列表 ↓↓
> 
> {wav_path}|{speaker_name}|{language}|{speaking text}{wav_path}|{speaker_name}|{语言}|{朗读文本} 派蒙_1.wav|派蒙|ZH|前面的区域，以后再来探索吧！学萌_1.wav|学萌|ZH|前区，那就回来探索吧！ tom-Brown_1.wav|tomBrown|EN|I am like beatles,you are not like? really?tom-Brown_1.wav|tomBrown|EN|我像披头士乐队，你真的不喜欢吗？ 佐藤さん_１番.wav|佐藤|JP|深海？いや深海の事なんかようわからんし、すまんね佐藤先生_No.1.wav|佐藤|JP|深海？不，我对深海了解不多，抱歉。 佐藤さん_2番.wav|佐藤|JP|早くご飯つくって～！お腹すいた佐藤先生_No.2.wav|佐藤|JP|我们快点做点吃的吧！我饿了
> 
> If you write |ZH| in the string in the esd.list file, which lists the datasets, training for Chinese will start automatically.如果您在列出数据集的 esd.list 文件中的字符串中写入 |ZH|，则中文训练将自动开始。
> 
> Prepare about 300~800 audio clips, each between 2 and 12 seconds long.准备大约 300~800 个音频片段，每个片段长度在 2 到 12 秒之间。 ![s](https://private-user-images.githubusercontent.com/141453555/394359030-d3a2e59a-c489-4021-8d11-02685e3af220.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDAxMDcsIm5iZiI6MTczMzg5OTgwNywicGF0aCI6Ii8xNDE0NTM1NTUvMzk0MzU5MDMwLWQzYTJlNTlhLWM0ODktNDAyMS04ZDExLTAyNjg1ZTNhZjIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNjUwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmQ2YTE2ZDE3ZWFjOWI2M2UzN2Q0MDU0MDMwMjY3ZjI1NzE3ZjVlMDFmYWYxNzJlMzM5NGMwMjk3ZWYxNTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zYLPy2c9Ai1H4I3ePAvR0hmjc2womhxfqXwk7k6JufM)

ok thks for teaching ,i ll try

**Comment by DomoMKT** [comment]
you're looking for a way to convert text into high-quality speech with low latency - i've got you covered! for that, i highly recommend checking out [www.nemesyslabs.com](https://www.nemesyslabs.com).
