### ISSUE TITLE
为什么要加数据增强？缺乏对照实验

### ISSUE THREAD

**Issue by splinter21** [Plachtaa/seed-vc#84]
![fc7f0589e94f69b1433e687c7fbebf29_SeedVC-train](https://github.com/user-attachments/assets/aa8122cb-971e-4a3e-ac18-e3757c939af6)

altered semantic用直接原始wav提特征，一样可以跑，那为啥要做数据增强？需要补充ab数据证明它的作用。

**Comment by Plachtaa** [comment]
你说得对
