### ISSUE TITLE
参考音频长度

### ISSUE THREAD

**Issue by zhengzhezhe** [Plachtaa/seed-vc#87]
想问下作者，这个参考音频长度不同对于转换效果影响大吗？最好用多长的音频作为ref_audio呢？

**Comment by Plachtaa** [comment]
empirically the longer reference audio is, the higher speaker similarity it produces, as long as it does not exceed context window (30s)

**Comment by zhengzhezhe** [comment]
> empirically the longer reference audio is, the higher speaker similarity it produces, as long as it does not exceed context window (30s)

好的，了解了，非常感谢！
还有一个问题哈，就是在finetune的时候会出现 "Warning: Skipped loading some keys due to shape mismatch: {input_pos}"  看了下发布的预训练模型里是8192，dufussion_transformer.py里写的是16384，这个warning会对转换效果有影响吗，需要把代码里也改成8192吗？

**Comment by Plachtaa** [comment]
it does not matter
