### ISSUE TITLE
real-time-gui.py  ImportError: cannot import name 'str2bool' from 'modules.commons'

### ISSUE THREAD

**Issue by micjac99** [Plachtaa/seed-vc#92]
modules/commons.py and modules-1.0.0 conflic
run real-time-gui.py 
1.(if sys package modules-1.0.0 installed ) 
   Traceback (most recent call last):
  File "E:\Seed-VC-V2\real-time-gui.py", line 21, in <module>
    from modules.commons import *
ModuleNotFoundError: No module named 'modules.commons'; 'modules' is not a package
    
2. (if  uninstalled package modules-1.0.0)
Traceback (most recent call last):
  File "E:\Seed-VC-V2\real-time-gui.py", line 31, in <module>
    from modules.commons import str2bool
ImportError: cannot import name 'str2bool' from 'modules.commons' (E:\Seed-VC-V2\modules\commons.py)

**Comment by micjac99** [comment]
where is "str2bool", can not find

**Comment by Plachtaa** [comment]
https://github.com/Plachtaa/seed-vc/blob/41404114fa33a690252d16b74f81f6c8dc146fb4/modules/commons.py#L10
